CREATE DATABASE ProyectoFinal_DB;
USE ProyectoFinal_DB;
SET LANGUAGE us_english;


-- TABLAS CATÁLOGO
CREATE TABLE EFECTO_SECUNDARIO(
	ID INT PRIMARY KEY IDENTITY,
	nombre VARCHAR(50) NOT NULL
);


CREATE TABLE ENFERMEDAD_CRONICA(
	ID INT PRIMARY KEY IDENTITY,
	nombre VARCHAR(50) NOT NULL,
);


CREATE TABLE INSTITUCION_ESENCIAL(
	ID INT PRIMARY KEY IDENTITY,
	nombre VARCHAR(50) NOT NULL
);


CREATE TABLE VACUNA(
	ID INT PRIMARY KEY IDENTITY,
	nombre VARCHAR(50) NOT NULL
);

CREATE TABLE DOSIS(
	ID INT PRIMARY KEY IDENTITY,
	nombre CHAR(20) NOT NULL
);


CREATE TABLE ESTABLECIMIENTO(
	ID INT PRIMARY KEY IDENTITY,
	nombre VARCHAR(50) NOT NULL
);


CREATE TABLE GENERO(
	ID INT PRIMARY KEY IDENTITY,
	genero CHAR(20)
);


CREATE TABLE NACIONALIDAD(
	ID INT PRIMARY KEY IDENTITY,
	nacionalidad VARCHAR(50)
);


CREATE TABLE DISCAPACIDAD(
	ID INT PRIMARY KEY IDENTITY,
	discapacidad CHAR(14)
)

CREATE TABLE COMORBILIDAD(
	ID INT PRIMARY KEY IDENTITY,
	comorbilidad CHAR(14)
);


-- CREANDO ENTIDADES
CREATE TABLE GESTOR(
	ID INT PRIMARY KEY IDENTITY,
	DUI CHAR(10) NOT NULL,
	fecha_de_nacimiento CHAR(8) NOT NULL,
	usuario VARCHAR(20) NOT NULL,
	contraseña VARCHAR(20) NOT NULL,
	nombres VARCHAR(50) NOT NULL,
	apellidos VARCHAR(50) NOT NULL,
	telefono CHAR(14) NOT NULL,
	correo_institucional VARCHAR(50) NOT NULL,
	direccion VARCHAR(50) NOT NULL,
	id_discapacidad INT NOT NULL, -- FK
	id_comorbilidad INT NOT NULL, -- FK
	id_genero INT NOT NULL -- FK
);


CREATE TABLE VACUNADOR(
	ID INT PRIMARY KEY IDENTITY,
	DUI CHAR(10) NOT NULL,
	fecha_de_nacimiento CHAR(8) NOT NULL,
	nombres VARCHAR(50) NOT NULL,
	apellidos VARCHAR(50) NOT NULL,
	telefono CHAR(14) NOT NULL,
	correo_institucional VARCHAR(20) NOT NULL,
	direccion VARCHAR(50) NOT NULL,
	id_discapacidad INT NOT NULL, -- FK
	id_comorbilidad INT NOT NULL, -- FK
	id_genero INT NOT NULL -- FK
);


CREATE TABLE CIUDADANO(
	ID INT PRIMARY KEY IDENTITY,
	DUI CHAR(10) NOT NULL,
	fecha_de_nacimiento CHAR(8) NOT NULL,
	nombres VARCHAR(50) NOT NULL,
	apellidos VARCHAR(50) NOT NULL,
	telefono CHAR(14) NOT NULL,
	correo_electronico VARCHAR(50) NOT NULL,
	direccion VARCHAR(50) NOT NULL,
	id_discapacidad INT NOT NULL, -- FK
	id_comorbilidad INT NOT NULL, -- FK
	id_genero INT NOT NULL, -- FK
	id_institucion_esencial INT NULL, -- FK
	id_enfermedad_cronica INT NOT NULL -- FK
);


CREATE TABLE MENOR(
	ID INT PRIMARY KEY IDENTITY,
	DUI_responsable CHAR(10) NOT NULL,
	fecha_de_nacimiento CHAR(8) NOT NULL,
	nombres VARCHAR(50) NOT NULL,
	apellidos VARCHAR(50) NOT NULL,
	telefono_responsable CHAR(14) NOT NULL,
	correo_electronico_responsable VARCHAR(50) NOT NULL,
	direccion_responsable VARCHAR(50) NOT NULL,
	id_discapacidad INT NOT NULL, -- FK
	id_comorbilidad INT NOT NULL, -- FK
	id_genero INT NOT NULL, -- FK
	id_institucion_esencial_responsable INT NULL, -- FK
	id_enfermedad_cronica INT NOT NULL -- FK
);


CREATE TABLE EXTRANJERO(
	ID INT PRIMARY KEY IDENTITY,
	pasaporte CHAR(9) NOT NULL,
	fecha_de_nacimiento CHAR(8) NOT NULL,
	nombres VARCHAR(50) NOT NULL,
	apellidos VARCHAR(50) NOT NULL,
	telefono CHAR(14) NOT NULL,
	correo_electronico VARCHAR(50) NOT NULL,
	direccion VARCHAR(50) NOT NULL,
	id_discapacidad INT NOT NULL, -- FK
	id_comorbilidad INT NOT NULL, -- FK
	id_genero INT NOT NULL, -- FK
	id_enfermedad_cronica INT NOT NULL, -- FK
	id_nacionalidad INT NOT NULL -- FK
);


CREATE TABLE CABINA(
	ID INT PRIMARY KEY IDENTITY,
	nombre VARCHAR(50) NOT NULL,
	telefono CHAR(14) NOT NULL,
	correo_electronico VARCHAR(50) NOT NULL,
	direccion VARCHAR(50) NOT NULL
);


-- TABLAS NxN
CREATE TABLE CITA(
	ID INT PRIMARY KEY IDENTITY,
	fecha CHAR(8) NOT NULL,
	hora CHAR(5) NOT NULL,
	id_establecimiento INT NOT NULL, --FK
	id_gestor INT NULL, --FK
	id_ciudadano INT NULL, --FK
	id_menor INT NULL, --FK
	id_extranjero INT NULL --FK
);


CREATE TABLE APLICAR_VACUNA(
	ID INT PRIMARY KEY IDENTITY,
	fecha CHAR(8) NOT NULL,
	hora CHAR(5) NOT NULL,
	id_dosis INT NOT NULL, --FK
	id_vacuna INT NOT NULL, -- FK
	id_efecto_secundario INT NOT NULL, --FK
	id_vacunador INT NOT NULL, -- FK
	id_gestor INT NOT NULL, -- FK
	id_ciudadano INT NULL, --FK
	id_menor INT NULL, --FK
	id_extranjero INT NULL --FK
);


CREATE TABLE INICIO_SESION(
	ID INT PRIMARY KEY IDENTITY,
	fecha_hora DATETIME NOT NULL,
	id_gestor INT NOT NULL,
	id_cabina INT NOT NULL,
);


-- NOTA:
-- CONSTRAINT PK_VacunanorxVacuna PRIMARY KEY (id_vacunador,id_vacuna), (ERROR: SOLO PERMITE INGRESAR UNA VEZ CADA COMBINACION DE ID DE VACUNADOR Y VACUNA
--CONSTRAINT PK_GestorxCabina PRIMARY KEY (id_gestor,id_cabina), (ERROR: SOLO PERMITE INGRESAR UNA VEZ CADA COMBINACION DE ID DE GESTOR Y CABINA) 


-- CREANDO LLAVES FORANEAS (FK)
-- establecimiento -> cita
ALTER TABLE CITA ADD FOREIGN KEY (id_establecimiento) REFERENCES ESTABLECIMIENTO(ID);
-- gestor -> cita
ALTER TABLE CITA ADD FOREIGN KEY (id_gestor) REFERENCES GESTOR(ID);
-- ciudadano -> cita
ALTER TABLE CITA ADD FOREIGN KEY (id_ciudadano) REFERENCES CIUDADANO(ID);
-- menor -> cita
ALTER TABLE CITA ADD FOREIGN KEY (id_menor) REFERENCES MENOR(ID);
-- extranjero -> cita
ALTER TABLE CITA ADD FOREIGN KEY (id_extranjero) REFERENCES EXTRANJERO(ID);
-- discapacidad -> gestor
ALTER TABLE GESTOR ADD FOREIGN KEY (id_discapacidad) REFERENCES DISCAPACIDAD(ID);
-- comorbilidad - > gestor
ALTER TABLE GESTOR ADD FOREIGN KEY (id_comorbilidad) REFERENCES COMORBILIDAD(ID);
-- genero -> gestor
ALTER TABLE GESTOR ADD FOREIGN KEY (id_genero) REFERENCES GENERO(ID);
-- discapacidad -> vacunador
ALTER TABLE VACUNADOR ADD FOREIGN KEY (id_discapacidad) REFERENCES DISCAPACIDAD(ID);
-- comorbilidad - > vacunador
ALTER TABLE VACUNADOR ADD FOREIGN KEY (id_comorbilidad) REFERENCES COMORBILIDAD(ID);
-- genero -> vacunador
ALTER TABLE VACUNADOR ADD FOREIGN KEY (id_genero) REFERENCES GENERO(ID);
-- discapacidad -> ciudadano
ALTER TABLE CIUDADANO ADD FOREIGN KEY (id_discapacidad) REFERENCES DISCAPACIDAD(ID);
-- comorbilidad - > ciudadano
ALTER TABLE CIUDADANO ADD FOREIGN KEY (id_comorbilidad) REFERENCES COMORBILIDAD(ID);
-- genero -> ciudadano
ALTER TABLE CIUDADANO ADD FOREIGN KEY (id_genero) REFERENCES GENERO(ID);
-- institucion_esencial -> ciudadano
ALTER TABLE CIUDADANO ADD FOREIGN KEY (id_institucion_esencial) REFERENCES INSTITUCION_ESENCIAL(ID);
-- enfermedad_cronica -> ciudadano
ALTER TABLE CIUDADANO ADD FOREIGN KEY (id_enfermedad_cronica) REFERENCES ENFERMEDAD_CRONICA(ID);
-- discapacidad -> menor
ALTER TABLE MENOR ADD FOREIGN KEY (id_discapacidad) REFERENCES DISCAPACIDAD(ID);
-- comorbilidad - > menor
ALTER TABLE MENOR ADD FOREIGN KEY (id_comorbilidad) REFERENCES COMORBILIDAD(ID);
-- genero -> menor
ALTER TABLE MENOR ADD FOREIGN KEY (id_genero) REFERENCES GENERO(ID);
-- institucion_esencial_responsable -> menor
ALTER TABLE MENOR ADD FOREIGN KEY (id_institucion_esencial_responsable) REFERENCES INSTITUCION_ESENCIAL(ID);
-- enfermedad_cronica -> menor
ALTER TABLE MENOR ADD FOREIGN KEY (id_enfermedad_cronica) REFERENCES ENFERMEDAD_CRONICA(ID);
-- discapacidad -> extranjero
ALTER TABLE EXTRANJERO ADD FOREIGN KEY (id_discapacidad) REFERENCES DISCAPACIDAD(ID);
-- comorbilidad - > extranjero
ALTER TABLE EXTRANJERO ADD FOREIGN KEY (id_comorbilidad) REFERENCES COMORBILIDAD(ID);
-- genero -> extranjero
ALTER TABLE EXTRANJERO ADD FOREIGN KEY (id_genero) REFERENCES GENERO(ID);
-- enfermerdad_cronica -> extranjero
ALTER TABLE EXTRANJERO ADD FOREIGN KEY (id_enfermedad_cronica) REFERENCES ENFERMEDAD_CRONICA(ID);
-- nacionalidad -> extranjero
ALTER TABLE EXTRANJERO ADD FOREIGN KEY (id_nacionalidad) REFERENCES NACIONALIDAD(ID);
-- dosis -> aplicar_vacuna
ALTER TABLE APLICAR_VACUNA ADD FOREIGN KEY (id_dosis) REFERENCES DOSIS(ID);
-- vacuna -> aplicar_vacuna
ALTER TABLE APLICAR_VACUNA ADD FOREIGN KEY (id_vacuna) REFERENCES VACUNA(ID);
-- efecto_secundario -> aplicar_vacuna
ALTER TABLE APLICAR_VACUNA ADD FOREIGN KEY (id_efecto_secundario) REFERENCES EFECTO_SECUNDARIO(ID);
-- vacunador -> aplicar_vacuna
ALTER TABLE APLICAR_VACUNA ADD FOREIGN KEY (id_vacunador) REFERENCES VACUNADOR(ID);
-- gestor -> aplicar_vacuna
ALTER TABLE APLICAR_VACUNA ADD FOREIGN KEY (id_gestor) REFERENCES GESTOR(ID);
-- ciudadano -> aplicar_vacuna
ALTER TABLE APLICAR_VACUNA ADD FOREIGN KEY (id_ciudadano) REFERENCES CIUDADANO(ID);
-- menor -> aplicar_vacuna
ALTER TABLE APLICAR_VACUNA ADD FOREIGN KEY (id_menor) REFERENCES MENOR(ID);
-- extranjero -> aplicar_vacuna
ALTER TABLE APLICAR_VACUNA ADD FOREIGN KEY (id_extranjero) REFERENCES EXTRANJERO(ID);
-- gestor -> inicio_sesion
ALTER TABLE INICIO_SESION ADD FOREIGN KEY (id_gestor) REFERENCES GESTOR(ID);
-- cabina -> inicio_sesion
ALTER TABLE INICIO_SESION ADD FOREIGN KEY (id_cabina) REFERENCES CABINA(ID);


-- INSERTAR DATOS EN EFECTO SECUNDARIO
INSERT INTO EFECTO_SECUNDARIO VALUES('--Seleccione--');
INSERT INTO EFECTO_SECUNDARIO VALUES('Dolor en el brazo');
INSERT INTO EFECTO_SECUNDARIO VALUES('Enrojecimiento en el brazo');
INSERT INTO EFECTO_SECUNDARIO VALUES('Hinchazon en el brazo');
INSERT INTO EFECTO_SECUNDARIO VALUES('Cansancio');
INSERT INTO EFECTO_SECUNDARIO VALUES('Dolor de cabeza');
INSERT INTO EFECTO_SECUNDARIO VALUES('Dolor muscular');
INSERT INTO EFECTO_SECUNDARIO VALUES('Escalofrios');
INSERT INTO EFECTO_SECUNDARIO VALUES('Fiebre');
INSERT INTO EFECTO_SECUNDARIO VALUES('Nauseas');
INSERT INTO EFECTO_SECUNDARIO VALUES('Ninguno');


-- INSERTAR DATOS EN ENFERMEDAD CRÓNICA
INSERT INTO ENFERMEDAD_CRONICA VALUES('--Seleccione--');
INSERT INTO ENFERMEDAD_CRONICA VALUES('Enfermedad Cardiovascular');
INSERT INTO ENFERMEDAD_CRONICA VALUES('Enfermedad Renal');
INSERT INTO ENFERMEDAD_CRONICA VALUES('Enfermedad Respiratoria');
INSERT INTO ENFERMEDAD_CRONICA VALUES('Diabetes');
INSERT INTO ENFERMEDAD_CRONICA VALUES('Cancer');
INSERT INTO ENFERMEDAD_CRONICA VALUES('Ninguna');


-- INSERTAR DATOS EN INSTITUCIÓN ESENCIAL
INSERT INTO INSTITUCION_ESENCIAL VALUES ('--Seleccione--');
INSERT INTO INSTITUCION_ESENCIAL VALUES ('Educacion');
INSERT INTO INSTITUCION_ESENCIAL VALUES ('Salud');
INSERT INTO INSTITUCION_ESENCIAL VALUES ('PNC');
INSERT INTO INSTITUCION_ESENCIAL VALUES ('Fuerza Armada');
INSERT INTO INSTITUCION_ESENCIAL VALUES ('Periodismo');
INSERT INTO INSTITUCION_ESENCIAL VALUES ('Personal de gobierno');
INSERT INTO INSTITUCION_ESENCIAL VALUES ('Ninguna');


-- INSERTAR DATOS EN VACUNA
INSERT INTO VACUNA VALUES ('--Seleccione--');
INSERT INTO VACUNA VALUES ('Pfizer-BioNTech');
INSERT INTO VACUNA VALUES ('AstraZeneca');
INSERT INTO VACUNA VALUES ('Moderna');
INSERT INTO VACUNA VALUES ('CoronaVac');


-- INSERTAR DATOS EN DOSIS
INSERT INTO DOSIS VALUES ('--Seleccione--');
INSERT INTO DOSIS VALUES ('Dosis 1');
INSERT INTO DOSIS VALUES ('Dosis 2');
INSERT INTO DOSIS VALUES ('Dosis 3');
INSERT INTO DOSIS VALUES ('Dosis 4');
INSERT INTO DOSIS VALUES ('Dosis 5');


-- INSERTAR DATOS EN ESTABLECIMIENTO
INSERT INTO ESTABLECIMIENTO VALUES ('--Seleccione--');
INSERT INTO ESTABLECIMIENTO VALUES ('Megacentro de vacunacion');
INSERT INTO ESTABLECIMIENTO VALUES ('Unidad de salud');
INSERT INTO ESTABLECIMIENTO VALUES ('Hospital');
INSERT INTO ESTABLECIMIENTO VALUES ('ISSS');


-- INSERTANDO DATOS EN DISCAPACIDAD
INSERT INTO DISCAPACIDAD VALUES ('--Seleccione--');
INSERT INTO DISCAPACIDAD VALUES ('Si');
INSERT INTO DISCAPACIDAD VALUES ('No');


-- INSERTANDO DATOS EN COMORBILIDAD
INSERT INTO COMORBILIDAD VALUES ('--Seleccione--');
INSERT INTO COMORBILIDAD VALUES ('Si');
INSERT INTO COMORBILIDAD VALUES ('No');


-- INSERTAR DATOS EN GÉNERO
INSERT INTO GENERO VALUES ('--Seleccione--');
INSERT INTO GENERO VALUES ('Masculino');
INSERT INTO GENERO VALUES ('Femenino');
INSERT INTO GENERO VALUES ('Indeterminado');
INSERT INTO GENERO VALUES ('No aplicable');


-- INSERTAR DATOS EN NACIONALIDAD
INSERT INTO NACIONALIDAD VALUES ('--Seleccione--');
INSERT INTO NACIONALIDAD VALUES ('Agana');
INSERT INTO NACIONALIDAD VALUES ('Alandés'); -- Åland provincia autónoma de Finlandia
INSERT INTO NACIONALIDAD VALUES ('Albanesa');
INSERT INTO NACIONALIDAD VALUES ('Alemana');
INSERT INTO NACIONALIDAD VALUES ('Andorrano');
INSERT INTO NACIONALIDAD VALUES ('Angolesa');
INSERT INTO NACIONALIDAD VALUES ('Anguilense');
INSERT INTO NACIONALIDAD VALUES ('Antártica');
INSERT INTO NACIONALIDAD VALUES ('Antiguana');
INSERT INTO NACIONALIDAD VALUES ('Argelina');
INSERT INTO NACIONALIDAD VALUES ('Argentina');
INSERT INTO NACIONALIDAD VALUES ('Armenio');
INSERT INTO NACIONALIDAD VALUES ('Arubeña');
INSERT INTO NACIONALIDAD VALUES ('Australiana');
INSERT INTO NACIONALIDAD VALUES ('Austriaca');
INSERT INTO NACIONALIDAD VALUES ('Azerbaiyana');
INSERT INTO NACIONALIDAD VALUES ('Bahameña');
INSERT INTO NACIONALIDAD VALUES ('Bangladesí');
INSERT INTO NACIONALIDAD VALUES ('Barbadense');
INSERT INTO NACIONALIDAD VALUES ('Bareiní');
INSERT INTO NACIONALIDAD VALUES ('Belga');
INSERT INTO NACIONALIDAD VALUES ('Beliceña');
INSERT INTO NACIONALIDAD VALUES ('Beninés');
INSERT INTO NACIONALIDAD VALUES ('Bermudeña');
INSERT INTO NACIONALIDAD VALUES ('Bielorrusa');
INSERT INTO NACIONALIDAD VALUES ('Birmano');
INSERT INTO NACIONALIDAD VALUES ('Boliviana');
INSERT INTO NACIONALIDAD VALUES ('Bosnia');
INSERT INTO NACIONALIDAD VALUES ('Botsuana');
INSERT INTO NACIONALIDAD VALUES ('Brasileña');
INSERT INTO NACIONALIDAD VALUES ('Británica');
INSERT INTO NACIONALIDAD VALUES ('Bruneano');
INSERT INTO NACIONALIDAD VALUES ('Búlgara');
INSERT INTO NACIONALIDAD VALUES ('Burkinés');
INSERT INTO NACIONALIDAD VALUES ('Burundés');
INSERT INTO NACIONALIDAD VALUES ('Butanés');
INSERT INTO NACIONALIDAD VALUES ('Caboverdiana');
INSERT INTO NACIONALIDAD VALUES ('Camboyana');
INSERT INTO NACIONALIDAD VALUES ('Camerunesa');
INSERT INTO NACIONALIDAD VALUES ('Canadiense');
INSERT INTO NACIONALIDAD VALUES ('Catarí');
INSERT INTO NACIONALIDAD VALUES ('Centroafricana');
INSERT INTO NACIONALIDAD VALUES ('Chadiana');
INSERT INTO NACIONALIDAD VALUES ('Checa');
INSERT INTO NACIONALIDAD VALUES ('Chilena');
INSERT INTO NACIONALIDAD VALUES ('China');
INSERT INTO NACIONALIDAD VALUES ('Chipriota');
INSERT INTO NACIONALIDAD VALUES ('Cocana');
INSERT INTO NACIONALIDAD VALUES ('Colombiana');
INSERT INTO NACIONALIDAD VALUES ('Comorana');
INSERT INTO NACIONALIDAD VALUES ('Congolesa'); -- la repiten
INSERT INTO NACIONALIDAD VALUES ('Cookiana');
INSERT INTO NACIONALIDAD VALUES ('Costarricense');
INSERT INTO NACIONALIDAD VALUES ('Croata');
INSERT INTO NACIONALIDAD VALUES ('Cubana');
INSERT INTO NACIONALIDAD VALUES ('Danesa');
INSERT INTO NACIONALIDAD VALUES ('De Isla Bouvet');
INSERT INTO NACIONALIDAD VALUES ('De Isla Navidad');
INSERT INTO NACIONALIDAD VALUES ('De Islas Heard y Mcdonald');
INSERT INTO NACIONALIDAD VALUES ('Dominicana');
INSERT INTO NACIONALIDAD VALUES ('Ecuatoguineano');
INSERT INTO NACIONALIDAD VALUES ('Ecuatoriana');
INSERT INTO NACIONALIDAD VALUES ('Egipcia');
INSERT INTO NACIONALIDAD VALUES ('Emiratí');
INSERT INTO NACIONALIDAD VALUES ('Eslovaca');
INSERT INTO NACIONALIDAD VALUES ('Eslovena');
INSERT INTO NACIONALIDAD VALUES ('Española');
INSERT INTO NACIONALIDAD VALUES ('Estadounidense');
INSERT INTO NACIONALIDAD VALUES ('Etíope');
INSERT INTO NACIONALIDAD VALUES ('Feroesa');
INSERT INTO NACIONALIDAD VALUES ('Filipina');
INSERT INTO NACIONALIDAD VALUES ('Finlandesa');
INSERT INTO NACIONALIDAD VALUES ('Fiyiana');
INSERT INTO NACIONALIDAD VALUES ('Francesa');
INSERT INTO NACIONALIDAD VALUES ('Francoguyanés');
INSERT INTO NACIONALIDAD VALUES ('Francopolinesio');
INSERT INTO NACIONALIDAD VALUES ('Gabonés');
INSERT INTO NACIONALIDAD VALUES ('Gambiana');
INSERT INTO NACIONALIDAD VALUES ('Georgina');
INSERT INTO NACIONALIDAD VALUES ('Georgina Del Sur');
INSERT INTO NACIONALIDAD VALUES ('Ghanesa');
INSERT INTO NACIONALIDAD VALUES ('Gibraltareña');
INSERT INTO NACIONALIDAD VALUES ('Granadina');
INSERT INTO NACIONALIDAD VALUES ('Griega');
INSERT INTO NACIONALIDAD VALUES ('Groenlandesa');
INSERT INTO NACIONALIDAD VALUES ('Guadalupeña');
INSERT INTO NACIONALIDAD VALUES ('Guameña');
INSERT INTO NACIONALIDAD VALUES ('Guatemalteca');
INSERT INTO NACIONALIDAD VALUES ('Guinea');
INSERT INTO NACIONALIDAD VALUES ('Guineana');
INSERT INTO NACIONALIDAD VALUES ('Guyanesa');
INSERT INTO NACIONALIDAD VALUES ('Haitiana');
INSERT INTO NACIONALIDAD VALUES ('Hindú');
INSERT INTO NACIONALIDAD VALUES ('Hondureña');
INSERT INTO NACIONALIDAD VALUES ('Hongkonés');
INSERT INTO NACIONALIDAD VALUES ('Húngara');
INSERT INTO NACIONALIDAD VALUES ('Indonesa');
INSERT INTO NACIONALIDAD VALUES ('Iraní');
INSERT INTO NACIONALIDAD VALUES ('Iraquí');
INSERT INTO NACIONALIDAD VALUES ('Irlandesa');
INSERT INTO NACIONALIDAD VALUES ('Islandesa');
INSERT INTO NACIONALIDAD VALUES ('Isleña De Pitcairn');
INSERT INTO NACIONALIDAD VALUES ('Isleña Ultramarina De Estados Unidos');
INSERT INTO NACIONALIDAD VALUES ('Israelí');
INSERT INTO NACIONALIDAD VALUES ('Italiana');
INSERT INTO NACIONALIDAD VALUES ('Jamaiquina');
INSERT INTO NACIONALIDAD VALUES ('Japonesa');
INSERT INTO NACIONALIDAD VALUES ('Jordana');
INSERT INTO NACIONALIDAD VALUES ('Kazajo');
INSERT INTO NACIONALIDAD VALUES ('Keniana');
INSERT INTO NACIONALIDAD VALUES ('Kirguiso');
INSERT INTO NACIONALIDAD VALUES ('Kiribatiano/a');
INSERT INTO NACIONALIDAD VALUES ('Kuwaití');
INSERT INTO NACIONALIDAD VALUES ('Laosiana');
INSERT INTO NACIONALIDAD VALUES ('Lesotense');
INSERT INTO NACIONALIDAD VALUES ('Letón');
INSERT INTO NACIONALIDAD VALUES ('Libanes');
INSERT INTO NACIONALIDAD VALUES ('Liberiana');
INSERT INTO NACIONALIDAD VALUES ('Libia');
INSERT INTO NACIONALIDAD VALUES ('Liechtenstense');
INSERT INTO NACIONALIDAD VALUES ('Lituana');
INSERT INTO NACIONALIDAD VALUES ('Luxemburguesa');
INSERT INTO NACIONALIDAD VALUES ('Macaense');
INSERT INTO NACIONALIDAD VALUES ('Macedonia');
INSERT INTO NACIONALIDAD VALUES ('Malauí');
INSERT INTO NACIONALIDAD VALUES ('Malayo');
INSERT INTO NACIONALIDAD VALUES ('Maldiva');
INSERT INTO NACIONALIDAD VALUES ('Malgache');
INSERT INTO NACIONALIDAD VALUES ('Malinese');
INSERT INTO NACIONALIDAD VALUES ('Maltesa');
INSERT INTO NACIONALIDAD VALUES ('Malvinensa');
INSERT INTO NACIONALIDAD VALUES ('Marfileña');
INSERT INTO NACIONALIDAD VALUES ('Marroquí');
INSERT INTO NACIONALIDAD VALUES ('Marshalesa');
INSERT INTO NACIONALIDAD VALUES ('Martinicana');
INSERT INTO NACIONALIDAD VALUES ('Mauriciana');
INSERT INTO NACIONALIDAD VALUES ('Mauritana');
INSERT INTO NACIONALIDAD VALUES ('Mayotense');
INSERT INTO NACIONALIDAD VALUES ('Mexicana');
INSERT INTO NACIONALIDAD VALUES ('Micronesia');
INSERT INTO NACIONALIDAD VALUES ('Moldava');
INSERT INTO NACIONALIDAD VALUES ('Monegasca');
INSERT INTO NACIONALIDAD VALUES ('Mongol');
INSERT INTO NACIONALIDAD VALUES ('Montserratiana');
INSERT INTO NACIONALIDAD VALUES ('Mozambiqueña');
INSERT INTO NACIONALIDAD VALUES ('Namibia');
INSERT INTO NACIONALIDAD VALUES ('Nauruana');
INSERT INTO NACIONALIDAD VALUES ('Neerlandés');
INSERT INTO NACIONALIDAD VALUES ('Neocaledonio');
INSERT INTO NACIONALIDAD VALUES ('Neozelandesa');
INSERT INTO NACIONALIDAD VALUES ('Nepalesa');
INSERT INTO NACIONALIDAD VALUES ('Nicaraguense');
INSERT INTO NACIONALIDAD VALUES ('Nigeriana');
INSERT INTO NACIONALIDAD VALUES ('Nigerina');
INSERT INTO NACIONALIDAD VALUES ('Niueño');
INSERT INTO NACIONALIDAD VALUES ('Norcoreana');
INSERT INTO NACIONALIDAD VALUES ('Norfolkense');
INSERT INTO NACIONALIDAD VALUES ('Normariana');
INSERT INTO NACIONALIDAD VALUES ('Noruega');
INSERT INTO NACIONALIDAD VALUES ('Omaní');
INSERT INTO NACIONALIDAD VALUES ('Pakistaní');
INSERT INTO NACIONALIDAD VALUES ('Palauana');
INSERT INTO NACIONALIDAD VALUES ('Palestina');
INSERT INTO NACIONALIDAD VALUES ('Panameña');
INSERT INTO NACIONALIDAD VALUES ('Papú');
INSERT INTO NACIONALIDAD VALUES ('Paraguaya');
INSERT INTO NACIONALIDAD VALUES ('Peruana');
INSERT INTO NACIONALIDAD VALUES ('Polaca');
INSERT INTO NACIONALIDAD VALUES ('Portuguesa');
INSERT INTO NACIONALIDAD VALUES ('Puertorriqueña');
INSERT INTO NACIONALIDAD VALUES ('Reunionés');
INSERT INTO NACIONALIDAD VALUES ('Ruandesa');
INSERT INTO NACIONALIDAD VALUES ('Rumaní');
INSERT INTO NACIONALIDAD VALUES ('Rusa');
INSERT INTO NACIONALIDAD VALUES ('Saharaui');
INSERT INTO NACIONALIDAD VALUES ('Salomonense');
INSERT INTO NACIONALIDAD VALUES ('Salvadoreña'); --???
INSERT INTO NACIONALIDAD VALUES ('Samoana'); -- la repiten
INSERT INTO NACIONALIDAD VALUES ('San Eleniana');
INSERT INTO NACIONALIDAD VALUES ('San Vicentina');
INSERT INTO NACIONALIDAD VALUES ('Sancristobaleña');
INSERT INTO NACIONALIDAD VALUES ('Sanmarinense');
INSERT INTO NACIONALIDAD VALUES ('Sanpedrino');
INSERT INTO NACIONALIDAD VALUES ('Santalucense');
INSERT INTO NACIONALIDAD VALUES ('Santotomense');
INSERT INTO NACIONALIDAD VALUES ('Saudí');
INSERT INTO NACIONALIDAD VALUES ('Senegalesa');
INSERT INTO NACIONALIDAD VALUES ('Seychellense');
INSERT INTO NACIONALIDAD VALUES ('Sierraleonesa');
INSERT INTO NACIONALIDAD VALUES ('Singapurense');
INSERT INTO NACIONALIDAD VALUES ('Siria');
INSERT INTO NACIONALIDAD VALUES ('Somalí');
INSERT INTO NACIONALIDAD VALUES ('Sueca');
INSERT INTO NACIONALIDAD VALUES ('Surcoreana');
INSERT INTO NACIONALIDAD VALUES ('Taiwanesa');
INSERT INTO NACIONALIDAD VALUES ('Trinidad y Tobago');
INSERT INTO NACIONALIDAD VALUES ('Turca');
INSERT INTO NACIONALIDAD VALUES ('Uruguaya');
INSERT INTO NACIONALIDAD VALUES ('Vaticana');
INSERT INTO NACIONALIDAD VALUES ('Venezolana');


-- INSERTAR DATOS EN CABINA
INSERT INTO CABINA VALUES ('Norte', '+503 2245-0873', 'cnorte@cabina.gob.sv', 'Megacentro de vacunacion');
INSERT INTO CABINA VALUES ('Sur', '+503 2245-0429', 'csur@cabina.gob.sv', 'Megacentro de vacunacion');
INSERT INTO CABINA VALUES ('Este', '+503 2245-3295', 'ceste@cabina.gob.sv', 'Megacentro de vacunacion');
INSERT INTO CABINA VALUES ('Oeste', '+503 2245-6438', 'coeste@cabina.gob.sv', 'Megacentro de vacunacion');
INSERT INTO CABINA VALUES ('Central', '+503 2245-8520', 'ccentral@cabina.gob.sv', 'Megacentro de vacunacion');


-- INSERTAR DATOS EN GESTOR
INSERT INTO GESTOR VALUES ('47593038-1', '03/05/92', 'pgonzalez', 'pgonzalez123', 'Pablo José', 'Gonzalez Ramirez', '+503 7032 8675', 'pgonzales@gestion.gob.sv', 'Lomas de San Francisco', 3, 3, 2);
INSERT INTO GESTOR VALUES ('58525654-0', '25/09/93', 'rflores', 'rflores123', 'Ramiro Miguel', 'Flores Aleman',  '+503 6139 3242', 'rflores@gestion.gob.sv', 'Antiguo Cuscatlan', 3, 3, 2);
INSERT INTO GESTOR VALUES ('73892340-2', '17/04/94', 'vquintanilla', 'vquintanilla123', 'Valeria Nohemi', 'Quintanilla Paz', '+503 7294 8521', 'vquintanilla@gestion.gob.sv', 'Santa Elena', 3, 3, 3);


-- INSERTAR DATOS EN VACUNADOR
INSERT INTO VACUNADOR VALUES ('68902753-5', '06/02/95', 'Paula Lucia', 'Lopez Ruiz', '+503 7032 8675', 'plopez@salud.gob.sv', 'Mejicanos', 3, 3, 3);
INSERT INTO VACUNADOR VALUES ('18593348-8', '28/11/96', 'Valeria Ximena', 'Perez Martinez', '+503 6158 4525', 'vperez@salud.gob.sv', 'Barrio San Jacinto', 3, 3, 3);
INSERT INTO VACUNADOR VALUES ('98393243-7', '19/10/97', 'Daniel Alejandro', 'Garcia Alvarez', '+503 7502-5295', 'dgarcia@salud.gob.sv', 'Colonia San Francisco', 3, 3, 2);


-- CONSULTAS:
SELECT * FROM EFECTO_SECUNDARIO;
SELECT * FROM INSTITUCION_ESENCIAL;
SELECT * FROM ENFERMEDAD_CRONICA;
SELECT * FROM VACUNA;
SELECT * FROM DOSIS;
SELECT * FROM ESTABLECIMIENTO;
SELECT * FROM GENERO;
SELECT * FROM NACIONALIDAD;
SELECT * FROM GESTOR;
SELECT * FROM VACUNADOR;
SELECT * FROM CIUDADANO;
SELECT * FROM MENOR;
SELECT * FROM EXTRANJERO;
SELECT * FROM CABINA;
SELECT * FROM CITA;
SELECT * FROM APLICAR_VACUNA;
SELECT * FROM INICIO_SESION;


-- CONEXIÓN CON VS
-- dotnet ef dbcontext scaffold ”Server=ANDREA; Database=ProyectoFinal_DB; Trusted_Connection=True; TrustServerCertificate=True;” Microsoft.EntityFrameworkCore.SqlServer -c ProyectoFinalContext

-- EN CASO DE GENERAR LAS ENTIDADES DESDE VS, PARA MIGRAR A SQL SERVER
-- dotnet ef migrations add init (migracion inicial)
-- dotnet ef migrations add changeN (migraciones -N)
-- dotnet ef database update changeN (actualiza la migracion -N en la BD)